### ISSUE TITLE
[Question] What scheme is used for integration

### ISSUE THREAD

**Issue by freakingwave** [capytaine/capytaine#272]
Hi Matthieu,

I was just wondering what scheme is used to calculate the integral of G/ dG over each panel in Capytaine?

Is it a Gauss quad integral? Then how many Gauss nodes are considered?

I went through the codes and it seems like the integral formulation should be written in Green_Rankine.f90, but I could not figure it out...

Can you point me out where I can find it?

Thank you & nice work on Capytaine!

**Comment by mancellin** [comment]
`Green_Rankine.f90` computes the $1/r$ terms of the Green function. Their integral over quadrilaterals are computed with an exact formula (except for distant points in which case a 1-point scheme is used.)

For the rest of the Green function in `Green_wave.f90`, the integration is done by default with a 1-point scheme. Their is an option to pass higher order quadrature schemes (see [this loop](https://github.com/capytaine/libDelhommeau/blob/3fea8d0f348e4e2f5b06d71a893b15da9f885c0e/src/matrices.f90#L166) and the `quad_points` and `quad_weights` arrays), but they must be computed beforehand. Based on my (few) tests, higher order quadratures increase a lot the computation time for a small precision gain.

**Comment by freakingwave** [comment]
Thanks for your useful reply. 

It surprises me that a 1-point scheme would work this well in frequency domain BEM.
I played around with time domain BEM with at least 8 point scheme to provide sufficient accuracy. I guess it has something to do with the free surface green function and mesh size. 

Thank you & the session can be closed.

**Comment by freakingwave** [comment]
Thank you for your detailed explaination. I need to go deeper at the codes. Seems complicated but interesting. 

Can you give some more insights on why capytaine follows a "exact fomulas" for panel integrals, rather than numerically calculating the integrals using a Gauss scheme? 
Like, first calculate the free surface green function values G(x) at finite points over a panel and evaluate the integral?

**Comment by mancellin** [comment]
The $1/r$ terms could indeed be integrated with a high-order Gauss scheme. It could be worth testing if a Gauss scheme has a better performance/precision compromise than the current analytical formulas. The current architecture comes mostly from Nemoh and I have no strong motivation to change it if it is not causing any issue.

Maybe your question is about why the Green function is integrated using two different schemes for different parts. It is because the $1/r$ is cheap to compute and needs a highly accurate scheme, whereas the rest ("wave part") is more expensive to compute but varies more slowly.

**Comment by freakingwave** [comment]
Excellent explaination. Appreciate your time and efforts. 

Thank you!
