### ISSUE TITLE
Higher order BEM 

### ISSUE THREAD

**Issue by austinerees** [capytaine/capytaine#286]
Hi everyone,
Greetings! I want to believe  capytaine was design for BEM with linear shape function alone.can it modified to accommodate higher order element via their shape function say for a cubic shape function?

Thank you in advance

Rees

**Comment by mancellin** [comment]
Higher-order methods in Capytaine have not really been thought out.

Do you have in mind something like the high-order method from WAMIT?
I believe, WAMIT's high-order method includes:
1. A representation of the geometry with curved panels instead of polygons;
2. A representation of the physical magnitude on this surface as spline function instead of assuming a constant value on each panel.

Both would require a fair amount of work to be implemented in Capytaine. (Point 1 is maybe more difficult than point 2, but I'm not sure.)

If you are motivated to work on that kind of things, I'd be happy to think a bit deeper about it and help you with it.

**Comment by austinerees** [comment]
Hi,
Any help with regards to this implementation would be helpful.Secondly,can one get a complete Theorectical manual to capytaine?

Thanks in advance

**Comment by mancellin** [comment]
Closing this thread since there has not been any new activity for a while. Feel free to reopen if you have a follow-up question or an issue.
