### ISSUE TITLE
Export rankine integration matrices and wave related matrices separately [Enhancement]

### ISSUE THREAD

**Issue by KapilKhanal** [capytaine/capytaine#452]
This has few benefits but mostly separating delhommeau's approximation (GF_wave) from the fundamental solution (-1/r-1/d) and also helps to verify and potentially improve upon rankine integration and include it separately. 

I am not a fortran user and was wondering if anyone already has a script modification to get those.  

Thanks,

**Comment by KapilKhanal** [comment]
just changing wavenumber = 0 when evaluating rankine will do this.
`green_function = Delhommeau()
engine = cpt.BasicMatrixEngine(linear_solver='direct')
#free_surface = np.infty gives rankine only
S,K = engine.build_matrices(mesh, mesh, free_surface = 0,  green_function = green_function,water_depth = np.infty,wavenumber = 0)`

**Comment by mancellin** [comment]
Yes, `wavenumber=0` will give you the sum of both Rankine terms without wave term:
```python
cpt.Delhommeau().evaluate(mesh1, mesh2, free_surface=0.0, water_depth=np.infty, wavenumber=0.0)
```
You should also get only the first Rankine term in the case without a free surface:
```python
cpt.Delhommeau().evaluate(mesh1, mesh2, free_surface=np.infty)
```

**Comment by KapilKhanal** [comment]
@mancellin neat, Capytaine supporting higher order derivatives of rankine terms for free surface and also for thin heave plates would be a great addition. I am also working on something similar which needs the higher order derivatives of both singular rankine and wave part of greens function.

**Comment by KapilKhanal** [comment]
@mancellin also if its exported separately , then the rankine + reflected_rankine can be stored in cache and only wave part can be run which should speed up the matrix computation.

**Comment by mancellin** [comment]
> @mancellin also if its exported separately , then the rankine + reflected_rankine can be stored in cache and only wave part can be run which should speed up the matrix computation for a list of omega user wants to calculate coefficients for.

I did that in early versions of Capytaine and, if I remember correctly, it was a 2% to 5% speedup. I reverted it later because:
1. it was getting in the way of [other stuffs I wanted to experiment](https://www.mdpi.com/1996-1073/17/2/372),
2. it was increasing the RAM consumption and thus limiting the size of maximal problems that could be solved.

Since then I changed the structure of the code which became a bit more modular, so 1. should not be a problem anymore and 2. could be worked-around by having two "engines": one slightly faster with more caching, and one requiring less RAM without caching.
