### ISSUE TITLE
Efficiently model multiple floating objects with H-matrices

### ISSUE THREAD

**Issue by lottevandongen** [capytaine/capytaine#51]
Dear Matthieu (or other Capytaine users),

I am using Capytaine for my thesis in Applied Mathematics to model a large number of floating (rectangular) objects, and I am espsecially interested in the influence they will have on the waves. Your Cookbook was really helpful for me to understand the functionalities available! Now I have 3 additional questions: 

- When increasing the number of floating objects, my code gives a memory error:
`MemoryError: Unable to allocate 5.38 GiB for an array with shape (19000, 19000) and data type complex128`
Therefore I was wondering whether you know of any projects which had a large number of objects (this was for n=50), and how they might have tackled this error. I'm also not sure which matrix it is that grows too large. The memory needed is independent on the number of frequencies and the problem is only for a single angle of incidence. The resolution and number of objects do effect the memory needed, but I couldn't find a clear relation yet. Below, I added a table which shows how the memory depends on these variables. 

- Are there possibilities to reduce the 3 dimensional problems to a problem in two dimensions (x,z)-space, such that you will get a vertical profile? Or is the only option to simply make the width of an object very long in (both + and -) y-direction and look at the velocity potential in the y=0 plane?

- When I use get_potential_on_mesh(), I get the error:
`TypeError: get_potential_on_mesh() missing 1 required positional argument: 'mesh'`
However, I have given a mesh of the free surface as 
`H=cpt.post_pro.free_surfaces.FreeSurface(x_range=(-50.0, 50.0), nx=10, y_range=(-50.0, 50.0), ny=10, name='test_surface')`
`cpt.bem.solver.BEMSolver.get_potential_on_mesh(results[0], H.mesh)`
and I also tried to use the mesh of the object as input (body.mesh). Do you have any suggestions to solve this or am I using the function the wrong way?

Thank you so much in advance. 

Kind regards,
Lotte van Dongen

![image](https://user-images.githubusercontent.com/63447681/113142306-06302680-922b-11eb-81a4-15970d2bcfda.png)

**Comment by mancellin** [comment]
Dear Lotte,

Thank you for your interest! Below are some answers to your questions:

- The BEM method require to compute an interaction between each panel of the mesh and all other panels. It means evaluating and inverting a matrix of size N × N where N is the number of panel in the mesh (that is the number of objects times the number of panels per object).
I have actually been working on a method to reduce the memory cost for applications such as yours: the interaction between distant objects can be simplified using a hierarchical matrix approximation of the huge matrix. There is a working prototype implemented in Capytaine, but I never had the time to complete the tests and the documentation. If you don't mind spending some time on possible remaining rough edges, we can try to apply it to your case.

- No, there is nothing implemented in the code to handle a true 2D problem. Mathematically, having very large bodies in the y direction should give you something close to a 2D problem, but I have no experience of computing this with Capytaine.

- You should call the method on an instance of `BEMSolver`, instead of the class `BEMSolver`:
```
solver = cpt.BEMSolver()
solver.get_potential_on_mesh(results[0], H.mesh)
```

**Comment by lottevandongen** [comment]
Dear Matthieu,

Thanks a lot for your quick answer! The matrix size indeed makes sense. I would be interested in the working prototype I think, then I can see how far I get. The floating objects are not located that far away from each other though; the gaps in between the objects are smaller than the object size. Would the hierarchical matrix approximation still work? 

Furthermore, I was wondering whether you have an explanation of how the linear matrix-vector problem is actually built up. I understand the theoretical concepts, but couldn't find the definition of the matrix and vector that are built. (I looked at bem.engines, for example build_matrices where matrices S and K are defined. Could you elaborate on what those are? )

Thanks,
Lotte

**Comment by RubendeBruin** [comment]
@lottevandongen , 
a bit off-topic:  you mentioned that this is a thesis project. If the gaps between the objects are small, did you think about how valid it is to use linear potential flow?

**Comment by mancellin** [comment]
> I would be interested in the working prototype I think

I'll post an example code here in the next days.

> Would the hierarchical matrix approximation still work?

Maybe not between an object and its immediate neighbor, but at least between an object and another distant one.

> I was wondering whether you have an explanation of how the linear matrix-vector problem is actually built up

See the "Theory manual" section of the documentation and the references in the bibliography there.
Another interesting reference is https://www.mdpi.com/2077-1312/7/3/81 (there are some differences in the method, but the main idea is mostly the same).

**Comment by mancellin** [comment]
Here is a code sample:
```python
import time
import numpy as np
import capytaine as cpt
import matplotlib.pyplot as plt

# GENERATE A PROBLEM WITH MANY BUOYS IN RANDOM POSITIONS
one_buoy = cpt.Sphere(radius=0.3, center=(0.0, 0.0, 0.0), ntheta=20, nphi=20, clever=False)
one_buoy.add_translation_dof(name="Heave")
one_buoy.keep_immersed_part()

nb_buoys = 40
buoys_positions = 20.0*np.random.rand(nb_buoys, 2)  # ! No check that there is no overlap of the buoys...
all_buoys = [one_buoy.copy(name="buoy_at_{:.2f}_{:.2f}".format(x, y)).translated([x, y, 0.0]) for (x, y) in buoys_positions]
all_buoys = cpt.FloatingBody.join_bodies(*all_buoys, name="many buoys")

all_buoys.show()
print("Total number of panels:", all_buoys.mesh.nb_faces)

some_dof = list(all_buoys.dofs.keys())[0]
problem = cpt.RadiationProblem(body=all_buoys, omega=1.0, radiating_dof=some_dof)

# DENSE SOLVER
start_time = time.perf_counter()
result = cpt.BEMSolver().solve(problem)
print("Dense resolution time: ", time.perf_counter() - start_time, "seconds")
ds1 = cpt.assemble_dataset([result])

# SPARSE SOLVER
sparse_engine = cpt.HierarchicalToeplitzMatrixEngine(ACA_distance=2.0, ACA_tol=1e-1)
sparse_solver = cpt.BEMSolver(engine=sparse_engine)
start_time = time.perf_counter()
other_result = sparse_solver.solve(problem)
print("Sparse resolution time: ", time.perf_counter() - start_time, "seconds")
ds2 = cpt.assemble_dataset([other_result])

print("Relative error: ", (ds1['added_mass'].data - ds2['added_mass'].data) / ds1['added_mass'].data.max())
```

The sparse solver might not always be worth it for a low number of panels, but it should always be faster and use less RAM for a very high number of panels.

If you'd like to go  deeper, some more tools to check the sparse representation of the matrix:
```python
# ACCESS THE SPARSE MATRIX
S, K = sparse_engine.build_matrices(all_buoys.mesh, all_buoys.mesh, 0.0, -np.infty, problem.wavenumber, cpt.Delhommeau())

print("{:.2f}% of the matrix is actually stored in memory".format(100 * K.density))

from itertools import cycle
K.display_color = cycle(["grey"])
K.plot_shape()
plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/31126826/114681212-389f5080-9d0e-11eb-8e3d-59f4d838d59f.png)

The plot represents a block matrix in which darker blocks are stored fully in memory, whereas the lighter blocks correspond to interaction between distant buoys and are approximated.
This is controlled by the parameters `ACA_distance` and `ACA_tol` in the code above. `ACA_distance` is the minimal relative distance between buoys to consider a sparse representation and `ACA_tol` is the tolerance on the error of the approximated blocks.

**Comment by marcogambarini** [comment]
@mancellin Thank you very much!

**Comment by mancellin** [comment]
If you can adapt the code sample above to your problem, I'd be interested to have some feedback on the efficiency of the method for you. In particular, on how does the parameters `ACA_tol` and `ACA_distance` affect the precision and the computation time on your problem.
In short, `ACA_tol` is a tolerance on the approximation of the interaction between distant objects (the higher `ACA_tol`, the sparser the matrix, the less accurate the simulation). `ACA_distance` is the distance under which the solver does not try to use an approximation (the higher `ACA_distance`, the most accurate and the less sparse the matrix).

**Comment by mancellin** [comment]
> I think a block-Toeplitz matrix could be built directly exploiting the geometry

Exactly. And that is actually probably what is happening in your results :)

I did not notice that you mentioned regular arrays in a previous message, so I did not talk about one of the feature: the `HierarchicalToeplitzMatrixEngine` is actually a try to combine both the use of H-matrices with the use of [block Toeplitz matrices for symmetric bodies](https://ancell.in/pdf/2018_OMAE_AD_7b4c6cfcdb.pdf).

If you generated your mesh with `assemble_regular_array`, the solver should be aware of the symmetry. You must be computing a block Toeplitz matrix with blocks that are either low-rank or dense depending on the ACA parameters. This would explain why the computation is still faster when `ACA_distance = 30` as basically no low-rank approximation is computed then.

Lately, my objective has been to document, test and advertise in priority the H-matrices and low-rank approximations (leaving aside any Toeplitz structure), since it is more widely applicable. But for your application using the Toeplitz solver would make sense.
Using both at the same time is tricky to tune. Based on your performance tests, using low-rank blocks (`ACA_distance` small) is sometimes faster and sometimes slower than having only dense blocks (`ACA_distance` large) in the block Toepiltz matrix...

**Comment by marcogambarini** [comment]
> I've been using ACA_distance=np.infty

Sorry for the late reply, thank you for the indication!

> I'm looking for goof values of ACA_tol and ACA_distance to try when it would work and only when it would work.

So, you mean finding a way to analyze the geometry and determine some bounds on the parameters?

**Comment by mancellin** [comment]
> So, you mean finding a way to analyze the geometry and determine some bounds on the parameters?

For now I am mostly looking for a default value that works well enough for most cases that users may come with. In theory, it should not depend much on the geometry. It might however depends on the wave frequency.

**Comment by mancellin** [comment]
Closing this thread since there has not been any new activity for a while. Feel free to reopen if you have a follow-up question or an issue.
