### ISSUE TITLE
Document how to get the pressure on each panel

### ISSUE THREAD

**Issue by mancellin** [capytaine/capytaine#517]
The documentation and the cookbook are missing examples on how to recover the pressure (and the velocity) on each panel of the body.

**Comment by mancellin** [comment]
Also add to the theory manual how the added mass and radiation damping are deduced for the pressure.

**Comment by izabala123** [comment]
Thank you very much, that's a good idea. 

I think it would be interesting if you also put some equations, to know how per-mesh-panel complex potentials, complex pressures, velocities, forces, added mass and radiation are related, because in this subject, unfortunately, there is no single criterion.

While anyone is free to save the matrices as and with any name they wish, you could also propose the names of the matrices to be saved from python to the .nc files,  so that they can be used later in a standard way.

Best regards
Iñaki

**Comment by mancellin** [comment]
Thank you @izabala123 for your comments.
You can check the state of the documentation on the master branch at https://capytaine.github.io/master/
In particular, I've just updated 
- https://capytaine.github.io/master/theory_manual/theory.html#forces-on-body-surfaces
- https://capytaine.github.io/master/user_manual/outputs.html#outputs-stored-in-linearpotentialflowresult
- https://capytaine.github.io/master/user_manual/cookbook.html#plot-pressure-on-hull
Let me know if you have any comments.

As for the inclusion in the NetCDF file, I'll think about it and open another thread.

**Comment by mancellin** [comment]
> As for the inclusion in the NetCDF file, I'll think about it and open another thread.

See #520
