### ISSUE TITLE
More Lid Questions

### ISSUE THREAD

**Issue by jtgrasb** [capytaine/capytaine#580]
I tested the internal lid feature with [WecOptTool's LUPA example](https://sandialabs.github.io/WecOptTool/_examples/tutorial_3_LUPA.html).
![image](https://github.com/user-attachments/assets/38c3242e-103b-4ce5-a431-915f7f7db497)

This example has a hole in it (moonpool) that causes a frequency spike to occur. I don't expect the lid to remove the spike due to the moonpool (because its a physical hole), but I tested it anyway. I found that adding the lid actually changes the result for added mass in the pitch direction. Can you explain why this would be the case? 
<img src="https://github.com/user-attachments/assets/048ba74a-5885-4888-b41d-6e3c6f847ca4" width="380"> <img src="https://github.com/user-attachments/assets/ab4df9a1-7d03-4f14-98b4-233152973eb9" width="380">

**Comment by mancellin** [comment]
Thank you for the feedback @jtgrasb!

I'm not sure to understand your physical problem. Is the moonpool due to the spar not completely filling the hole in the float? So you're adding a lid on this annular section?

Independently of lid meshes, thin heave plates are known to cause some issue if the mesh convergence is insufficient.
Otherwise, I've no idea how to explain your Pitch results.

**Comment by jtgrasb** [comment]
Thanks for the response @mancellin. You have a great point, the moonpool is not fully filled by the spar body, which I didn't realize. By changing the diameter of the hole to be match the spar, I was able to remove the frequency spikes.
