### ISSUE TITLE
Inertia Matrix Calculation in Capytaine

### ISSUE THREAD

**Issue by riasatmorshed** [capytaine/capytaine#581]
Hello!

I was wondering how Capytaine is calculating the inertia matrix and I was trying to see if it can generate the same inertia matrix for a well-known and well-defined Oscillating Surge Wave Energy Converter (OSWEC) which is defined in the WECSim Tutorial case. The link to the geometry is this: [https://wec-sim.github.io/WEC-Sim/dev/user/tutorials.html#oscillating-surge-wec-oswec](url)

In my code, I have also defined the mass as is retrieved from the WECSim tutorial webpage which reads like this: 
`oswec_flap = cpy.FloatingBody(mesh=oswec_flap_mesh.keep_immersed_part(), dofs=cpy.rigid_body_dofs(),center_of_mass = (0, 0, -3.9), mass= 127000)`.
A note here is to make the clipping accurate I have translated the mesh to 0.1m in positive z direction, other than that, the mesh file is obtained from the WECSim directory, that is to say, I have used their mesh file. But not a single element of the inertia matrix is not what is described in the tutorial, let alone (5,5) element which is supposed to be the Pitch Moment of Inertia. Is there anything that I am missing? Thank you!

The output is this: 
`array([[ 1.27000000e+05,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -0.00000000e+00],
       [ 0.00000000e+00,  1.27000000e+05,  0.00000000e+00,
        -0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.27000000e+05,
         0.00000000e+00, -0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
         3.82311279e+06,  6.04703579e-12, -0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
         6.04703579e-12,  9.14156017e+05,  6.05201846e-02],
       [-0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -0.00000000e+00,  6.05201846e-02,  2.96557165e+06]])`

[capytaine_issue02.zip](https://github.com/user-attachments/files/16554959/capytaine_issue02.zip)

**Comment by mancellin** [comment]
First, keep I mind that inertia matrix is almost out of the scope of Capytaine. Because it depends on the distribution of mass within the body, which is not handled by a fluid dynamics code such as Capytaine. The method to compute inertia matrix in Capytaine is there for teaching and testing, but does not cover all the possible relevant cases. The mass is assumed to be uniform within the body. Could this explain your discrepancy?

Also check if you computed the inertia matrix before or after you clipped the mesh. The emerged part need to be discarded for fluid-structure interaction, but it is relevant for the inertia matrix.

**Comment by riasatmorshed** [comment]
@mancellin Thanks for your response- I really appreciate it. I double-checked my geometry and found what was causing trouble. The issue was computing inertia matrix before and after clipping the mesh. So if center of mass and etc. etc. are defined properly, for a uniform geometry with uniform mass density, Capytaine can accurately compute the inertia matrix.
